# Generated by Django 2.0.6 on 2019-03-11 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='ruta',
            new_name='url_image',
        ),
        migrations.RemoveField(
            model_name='talla',
            name='nombre',
        ),
        migrations.AddField(
            model_name='foto',
            name='Type_Image',
            field=models.CharField(choices=[('SLD', 'SLYDER'), ('PRC', 'PRINCIPAL')], default='SLD', max_length=3),
        ),
        migrations.AddField(
            model_name='talla',
            name='talla',
            field=models.CharField(choices=[('CHI', 'CHICA'), ('MED', 'MEDIANA'), ('GRD', 'GRANDE')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
